# Generated by Django 4.1.1 on 2022-10-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
